### ISSUE TITLE
Executing Infinite Yield Reborn takes me to the game Adopt Me.

### ISSUE THREAD

**Issue by lamnguyenphuc** [fuckusfm/infiniteyield-reborn#14]
Whenever at now, I execute the script IY Reborn it just takes me to the game Adopt Me, at any game, anytime for now. Before it was working and doesn't teleport me to the game but now it just teleport me to Adopt Me.

**Comment by fuckusfm** [comment]
fixed already

**Comment by lamnguyenphuc** [comment]
> fixed already

but now it still does it

**Comment by lamnguyenphuc** [comment]
lemme try again

**Comment by lamnguyenphuc** [comment]
nope it still does it

**Comment by RyXeleron** [comment]
you just doxxed yourself with that goofy ahh username
